# https://salsa.debian.org/debian/wpa/-/blob/debian/unstable/wpa_supplicant/wpa_supplicant.conf
ctrl_interface=/var/run/wpa_supplicant

country=IT

network={
	ssid="YourSSID"
	psk="YourPreSharedKey"
}
